services:
  postgres:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"

  backend:
    image: registry.gitlab.com/miqueiasmiguel/honorare/backend:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=honorare;Username=honorare;Password=${POSTGRES_PASSWORD}"

  admin-web:
    image: registry.gitlab.com/miqueiasmiguel/honorare/admin-web:latest

  medico-pwa:
    image: registry.gitlab.com/miqueiasmiguel/honorare/medico-pwa:latest

  otel-collector:
    ports: []

  jaeger:
    ports: []

  prometheus:
    ports: []

  loki:
    ports: []

  grafana:
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_AUTH_DISABLE_LOGIN_FORM: "false"
    ports: []
